vae_checkpoint: checkpoints/vit-l-20.safetensors
pretrained_model: checkpoints/oasis500m.safetensors
model_name: dit_continue_action
learning_rate: 1e-4
min_learning_rate: 1e-4
warnup_ratio: 0.05
batch_size: 16
gradient_accumulation_steps: 1
validation_batch_size: 16
dataset_type: hfdataset

weight_decay: 0.0


num_epochs: 10
max_steps: -1  
validation_steps: 10000
save_every: 10000
output_dir: checkpoints
logging_steps: 10

seed: 42
use_wandb: true

ddim_noise_steps:  50
ddim_noise_steps_inference: 100
ctx_max_noise_idx:  4 
noise_abs_max: 20.0
n_prompt_frames: 4

resume_from_checkpoint: true

use_action_conditioning: true